### PR TITLE
Add new hosting option

### PR DESCRIPTION
**Pull request by tianheg**

### CODE REVIEW

**Comment by sissbruecker** [comment]
@tianheg Thanks! Do you have a Github repo where people could take a look at how the template is configured?

**Comment by tianheg** [comment]
I have made a repo which has more info https://github.com/tianheg/linkding-on-railway , maybe it's better to replace

```md
- [Railway.app](https://railway.app/) - Deploy linkding through [template](https://railway.app/template/BxdomX). By [tianheg](https://github.com/tianheg)
```

with

```md
- [linkding on railway.app](https://github.com/tianheg/linkding-on-railway) - Guide for hosting a linkding installation on [railway.app](https://railway.app/). By [tianheg](https://github.com/tianheg)
```

---

What should I do to update it?

**Comment by sissbruecker** [comment]
Sorry, it wasn't clear to me how Railway templates work. I was assuming there would be a template file or configuration file or something, in which case it's nice if people can take a look and verify what it does under the hood.
But taking a closer look it seem that Railway templates are only configured in the Railway UI, and when you create an app from a template you see all the configuration from the template in the UI again. Did I understand that correctly?

Regarding changing the link, I'd be in favor of that, then people can reach out to you directly if they have any questions or requests about the template. Would be great if you could open another PR.

**Comment by tianheg** [comment]
> But taking a closer look it seem that Railway templates are only configured in the Railway UI, and when you create an app from a template you see all the configuration from the template in the UI again. Did I understand that correctly?

Yes

> Regarding changing the link, I'd be in favor of that, then people can reach out to you directly if they have any questions or requests about the template. Would be great if you could open another PR.

I'll do that shortly

**Pull request merged**
