### PR TITLE
Issue #132 - show URL in bookmark list

### PR DESCRIPTION
**Pull request by clach04**
Kudos to https://github.com/gingerbeardman

### CODE REVIEW

**Comment by sissbruecker** [comment]
I'm not totally against displaying the URL in the overview, but at this point it has to be optional. Not everyone wants or needs this, and people like linkding because it's minimal and unobtrusive, so I'm very hesitant to add more elements by default. Apart from that it needs several improvements to the UX and it needs to be covered by automated tests. So in order to adopt this feature I would like the following changes:
- Make displaying the URL optional. It can be enabled in the settings.
- By default the URL is not displayed
- Move the URL into a new line below the title, rather than into the line that contains the description
- Ensure that the line is truncated with elipsis if there is not enough screen space to display the full URL, and ensure that the URL never wraps into a second line or overflows to the right
- Add unit tests to verify that the URL is only visible when the respective setting is enabled, and that it properly displays and links to the URL

**Review by sissbruecker — CHANGES_REQUESTED** [review]
I'm not totally against displaying the URL in the overview, but at this point it has to be optional. Not everyone wants or needs this, and people like linkding because it's minimal and unobtrusive, so I'm very hesitant to add more elements by default. Apart from that it needs several improvements to the UX and it needs to be covered by automated tests. So in order to adopt this feature I would like the following changes:
- Make displaying the URL optional. It can be enabled in the settings.
- By default the URL is not displayed
- Move the URL into a new line below the title, rather than into the line that contains the description
- Ensure that the line is truncated with elipsis if there is not enough screen space to display the full URL, and ensure that the URL never wraps into a second line or overflows to the right
- Add unit tests to verify that the URL is only visible when the respective setting is enabled, and that it properly displays and links to the URL

**Comment by clach04** [comment]
Sounds good, great suggestions! I'll dig into Django a little and see what I can figure out (it's been a while since I used it), could be a while before you see movement on my end.

**Comment by clach04** [comment]
TODO based on https://github.com/sissbruecker/linkding/pull/219#pullrequestreview-922297254

  * Make displaying the URL optional. It can be enabled in the settings.
  * By default the URL is not displayed
  * (/) Move the URL into a new line below the title, rather than into the line that contains the description
  * Ensure that the line is truncated with elipsis if there is not enough screen space to display the full URL, and ensure that the URL never wraps into a second line or overflows to the right
  * Add unit tests to verify that the URL is only visible when the respective setting is enabled, and that it properly displays and links to the URL

**Comment by sissbruecker** [comment]
Closing this as stale for now.

**Pull request closed without merging**
