### PR TITLE
Add apache reverse proxy documentation.

### PR DESCRIPTION
**Pull request by jhauris**
Also includes a docker-compose example, and minimal vhost configuration.

### CODE REVIEW

**Comment by sissbruecker** [comment]
Thanks for testing this! I'm not so sure about maintaining the whole Apache setup from this PR though (Dockerfile, full Apache config + Vhost config). I think it would be enough to just inline the virtual host config into the Readme details section as an example. Alternatively you could put the setup in your own repo, and we can link to that from the Readme. What do you think?

**Comment by jhauris** [comment]
> Thanks for testing this! I'm not so sure about maintaining the whole Apache setup from this PR though (Dockerfile, full Apache config + Vhost config). I think it would be enough to just inline the virtual host config into the Readme details section as an example. Alternatively you could put the setup in your own repo, and we can link to that from the Readme. What do you think?

That makes sense. Let me re-work this PR as you suggest:
* add the virtual host config to the ReadMe
* Create a tag in my repo in the branch with the docker compose setup
* add a link in the ReadMe to the configuration in my repo

Thank you for the suggestion!

**Comment by jhauris** [comment]
This PR now only includes updates to the Readme. If you don't like the link to my repo, we can just cut out the last commit.

**Comment by sissbruecker** [comment]
Looks good, thanks.

**Pull request merged**
