### PR TITLE
refactor: fetch site metadata asynchronously when saving

### PR DESCRIPTION
**Pull request by tecoholic**
## Description

The PR makes fetching the site metadata (title, description) asynchronously when creating and updating the Bookmarks. 

## Problem

I noticed that saving bookmarks using the browser extension on my self-hosted instance was taking way too long, sometimes even 10 seconds.

Sample: **5.92 seconds**
sync_extension_hosted

The core problem seems to be that fetching the URL, parsing the content in BeautifulSoup, setting the metadata, all seem to be happening in the Request-Response cycle of saving a Bookmark.

## Solution

In this PR, the issue is solved by making the `_update_website_metadata` run asynchronously.

## Results

The Bookmark create and update requests happen in a fraction of the time as before. Below are screenshots of some comparisons

All the following tests were performed with linkding running on local machine and the save Wikipedia link was saved.

#### Before - 510ms
|sync|
|-|

#### After - 180ms
|async|
|-|

#### Before - 951ms

|sync_extension|
|-|

#### After - 113ms

|async_extenstion|
|-|

### CODE REVIEW

**Comment by tecoholic** [comment]
@sissbruecker Happy holidays. :christmas_tree:  Kindly take a look at this PR when you get some time after the vacation.

**Comment by sissbruecker** [comment]
Thanks, it's an interesting idea, however there are some issues with it:
- When using the add bookmark form, the user gets redirected to the bookmark list after saving. Here they will only see the URL for the newly added bookmark, making it look like the website scaping is broken.
- Similarly, when having a large backlog of background tasks (e.g. after bookmark import), it could take a long time until the scaping eventually happens
- Background tasks can be disabled completely, which [some users might have done](https://github.com/sissbruecker/linkding/issues/157#issuecomment-1007706160):
https://github.com/sissbruecker/linkding/blob/2e3010d522003a13c39abd72cca3ce6c75c96ab5/bootstrap.sh#L19-L22

If anything, this should be an optional behavior, and there would need to be something in the bookmark list that indicates that the bookmark has not been scaped yet.

Personally, I'm currently more interested in making the scraping faster:
- https://github.com/sissbruecker/linkding/pull/354 - This change has already been merged, but is not released yet. Rather than loading the full HTML document, the scaper now stops loading after detecting the end of the head tag or after loading a fixed amount of data. This should help quite a bit.
- Another option I have been considering is skipping scraping on save. Currently when using the in-app bookmark form, the scaping actually runs twice: Once when opening the form, to show previews for website title and description, and a second time when saving the bookmark. If the form already has scraped the title and description, then the server shouldn't need to scape again, and instead the values could just be provided by the form. This would require some additional work to do the same for the extension.

**Comment by tecoholic** [comment]
@sissbruecker Thank you for explaining the situation more clearly. I did miss the part in the documentation which says, the background tasks can be turned off. Regarding the 2 alternates you have mentioned here:

1. Limiting the document size of the website scrapper - I think this is such a great improvement and will definitely help bring down those times. :clap:
2. Preventing double scraping - Can't we do something simpler like using a `@functools.cache` to achieve the same? I will investigate this and open a separate PR if that is a possible solution.

I am closing this PR for now. :)

**Comment by sissbruecker** [comment]
Thanks, temporarily caching the meta data might actually be a much easier alternative.

**Pull request closed without merging**
