### PR TITLE
Issue 220 qrcode support

### PR DESCRIPTION
**Pull request by clach04**

### CODE REVIEW

**Comment by clach04** [comment]
Any interest in this as a feature? This change is not ready for merging! It needs hitting with a pretty stick so that the qrcode is less obtrusive.

This relies on qrcode.min.js from https://github.com/davidshimjs/qrcodejs to be present in the `bookmarks/static/` directory.

**Comment by clach04** [comment]
image
Screen shot

**Comment by sissbruecker** [comment]
@clach04 

> Any interest in this as a feature? 

You would need to make an argument for why this should be added. Who would benefit from something like this, what is the use case? People like linkding because it's minimal and unobtrusive, so the idea is to rather have less features that benefit a lot of people, rather than add all the features that only benefit very few. Especially when that feature would be very obtrusive by taking up a lot of screen space in some manner, or would add extra depencies such as the JS that generates the QR code.

**Comment by clach04** [comment]
@sissbruecker Main use case for me is sharing URLs to friends/coworkers who do not have network access to my instance (or I don't want to give them access) but we have a laptop/TV/phone/tablet in the room to share the qr-code to a phone/tablet.

Shaarli has support for this and the qr code is NOT visible by default, you have to click on a small icon which is a nice way of doing this (my initial hack was to simply just display them all the time super big! :)) Screenshot below in case that's helpful:

image

Shaarli's support is via plugins which leads to one possible idea, any interest in a plugin in architecture for LinkDing? Or would that be too heavyweight? That would change the way one would approach this (and potentially even #219).

Either way, I'm happy running a customized instance of LinkDing so if this isn't useful you've given me the base I need to get the features I want/need :-) Thanks for making this available! I'm currently a reluctant user of Shaarli, it has some of the features I want but it's deployment/storage is not my preference, I like LinkDing's deployment/storage model and it's easier for me to hack on to get the features I want so I'm partway through migrating :)

**Comment by clach04** [comment]
Screen shots of current progress, click to show/hide implemented.

## regular view

image

## clicked

image

**Comment by sissbruecker** [comment]
Thanks for your effort, but I don't want to go ahead with this ATM. Adding another dependency to the app for this is a bit too much IMO, and sharing links is still reasonable easy.

One suggestion I can make is to turn this into a browser extension, and then see if people are interested in this. If this turns out to be popular, then it would be more reasonable to integrate it into the app.

**Comment by clach04** [comment]
On Firefox desktop https://github.com/rugk/offline-qr-code is a good generic (rather than LinkDing specific) browser extension alternative/workaround (doesn't work on mobile though)

**Comment by sissbruecker** [comment]
@clach04 Feel free to mention this in #220 as well, as that is more discoverable for other users.

**Pull request closed without merging**
