### PR TITLE
Add API endpoint (`api/bookmarks/export`) to allow exporting the bookmarks in netscape html format

### PR DESCRIPTION
**Pull request by obrhubr**
I am not familiar at all with Django development, but I wanted this feature for personal use. Because your project doesn't really have any guidelines for contributing, I don't know what you expect from a pull request (or if you even accept any).

I would be willing to add to my changes to make my branch ready for merging.

### CODE REVIEW

**Comment by radiant-tangent** [comment]
There is an export feature in settings that uses the `/settings/export` endpoint. How does this improve upon that functionality?

**Comment by obrhubr** [comment]
The export endpoint under `/settings/export` is restricted to session based authentication. It's not a REST endpoint meant to be accesses programmatically by a script.
Session based auth is only possible through the CSRF protected login enpoint for linkding.
This PR improves on that by providing this functionality as a REST API.

**Comment by sissbruecker** [comment]
I assume you want to use this for backups? I'm not sure if I want to encourage that by providing an option to automate this through the API. The export is quite limited in what it supports, and I'd rather encourage to use the actual backup mechanism described in the docs.

**Comment by DonkeeeyKong** [comment]
> I assume you want to use this for backups? I'm not sure if I want to encourage that by providing an option to automate this through the API. The export is quite limited in what it supports, and I'd rather encourage to use the actual backup mechanism described in the docs.

I think, It would be nice to have this not in place of but in addition to a standard backup as an 'emergency backup' for the worst case scenario: For some reason linkding stops working and I can't get it back. 
In this scenario, if I had automated exports to a standardized format enabled, it would be easily possible to access my bookmarks from somewhere else or just import them quickly into e.g. my browser.
As the bookmarks are the most important item to be backed up, this would be a good fall-back option.

**Pull request closed without merging**
